
name: CI Build

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      submodule:
        description: The directory of the submodule, if this workflow is being called on a submodule
        required: true
        type: string

jobs:   
  build-modern:
    name: miyooctl for MiyooCFW (musl)
    runs-on: ubuntu-22.04
    container:
      image: miyoocfw/toolchain-shared-musl:master
    steps:
    - run: echo "submodule ${{ inputs.submodule }} on ${{ github.event }}"
    - uses: actions/checkout@v4
    - if: inputs.submodule
      run: git submodule update --init --depth 1 -- ${{ inputs.submodule }}
    - name: build
      run: cd ${{ inputs.submodule || '.' }} && make
    - uses: actions/upload-artifact@v4
      with:
        name: miyooctl (musl)
        path: ${{ inputs.submodule || '.' }}/miyooctl
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  build-legacy:
    name: miyooctl for MiyooCFW (uClibc)
    runs-on: ubuntu-22.04
    container:
      image: miyoocfw/toolchain-shared-uclibc:master
    steps:
    - run: echo "submodule ${{ inputs.submodule }} on ${{ github.event }}"
    - uses: actions/checkout@v4
    - if: inputs.submodule
      run: git submodule update --init --depth 1 -- ${{ inputs.submodule }}
    - name: build
      run: cd ${{ inputs.submodule || '.' }} && make
    - uses: actions/upload-artifact@v4
      with:
        name: miyooctl (uClibc)
        path: ${{ inputs.submodule || '.' }}/miyooctl
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`